DROP TABLE IF EXISTS `PURCHASES`;

DROP TABLE IF EXISTS `POINT_HISTORIES`;

DROP TABLE IF EXISTS `POINT_SOURCES`;

DROP TABLE IF EXISTS `EVENTS_TO_CLUBS`;

DROP TABLE IF EXISTS `EVENTS`;

DROP TABLE IF EXISTS `EVENT_VERSIONS`;

DROP TABLE IF EXISTS `CLUB_MEMBERS`;

DROP TABLE IF EXISTS `CLUBS`;

DROP TABLE IF EXISTS `STUDENTS_TO_INTERESTS`;

DROP TABLE IF EXISTS `INTERESTS`;

DROP TABLE IF EXISTS `STUDENT_INFO`;

DROP TABLE IF EXISTS `STUDENTS`;