DROP TABLE IF EXISTS `EVENT_DESCRIPTIONS`;

DROP TABLE IF EXISTS `EVENT_TAGS`;

DROP TABLE IF EXISTS `EVENTS_TO_CLUBS`;

DROP TABLE IF EXISTS `EVENT_IMAGES`;

DROP TABLE IF EXISTS `CLUB_MEMBERS`;

DROP TABLE IF EXISTS `CLUB_INFO`;

DROP TABLE IF EXISTS `STUDENT_INFO`;

DROP TABLE IF EXISTS `VERIFIED_CLUBS`;

DROP TABLE IF EXISTS `ADMINS`;

DROP TABLE IF EXISTS `EVENTS`;

DROP TABLE IF EXISTS `STUDENTS`;

DROP TABLE IF EXISTS `CLUBS`;

DROP TABLE IF EXISTS `IMAGES`;